const CENTRAL_AGF_CFG = Object.freeze({
  VERSION: '0.2.0',
  TIMEZONE: 'America/Sao_Paulo',
  PROPS: Object.freeze({
    QUERY_SPREADSHEET_ID: 'CENTRAL_AGF_QUERY_SPREADSHEET_ID',
    CONTROL_SPREADSHEET_ID: 'CENTRAL_AGF_CONTROL_SPREADSHEET_ID',
    MASTER_SPREADSHEET_ID: 'CENTRAL_AGF_MASTER_SPREADSHEET_ID'
  }),
  FILE_NAMES: Object.freeze({
    QUERY: 'CONSULTA_HISTORICA_POSTAGENS',
    CONTROL: 'CONTROLE_CARGAS_POSTAGENS',
    MASTER: 'CADASTRO_MESTRE_CLIENTES'
  }),
  SHEETS: Object.freeze({
    PANEL: '00_PAINEL',
    PARAMS: '01_PARAMETROS',
    CLIENTS: '02_CLIENTES',
    POSTS: '03_POSTAGENS',
    AUDIT_CENTER_LOCAL: '04_AUDITORIA_CENTRO_LOCAL',
    DIVERGENCES: '05_DIVERGENCIAS',
    PARTITION_CATALOG_VIEW: '06_CATALOGO_PARTICOES',
    HOMOLOGATION: '07_HOMOLOGACAO',
    READ_FIRST: '08_LEIA_PRIMEIRO',
    PARTITION_CATALOG_SOURCE: '03_PARTICOES',
    FACTS: '01_FATOS',
    MASTER_CLIENTS: '01_CLIENTES_MASTER'
  }),
  QUERY: Object.freeze({
    WRITE_CHUNK_ROWS: 2500,
    HARD_MAX_ROWS: 500000,
    DEFAULT_MODE: 'POSTAGENS',
    ALLOW_ORIGIN_FALLBACK: true
  }),
  AUDIT: Object.freeze({
    BILLING_TOLERANCE: 0.01,
    SRO_REGEX: /^[A-Z]{2}\d{9}BR$/,
    SPECIAL_OBJECTS: Object.freeze(['SEM_REGISTRO', 'PRODUTO_ECT'])
  })
});
