const CENTRAL_AGF_CFG = Object.freeze({
  VERSION: '0.9.0',
  TIMEZONE: 'America/Sao_Paulo',
  PROPS: Object.freeze({
    QUERY_SPREADSHEET_ID: 'CENTRAL_AGF_QUERY_SPREADSHEET_ID',
    CONTROL_SPREADSHEET_ID: 'CENTRAL_AGF_CONTROL_SPREADSHEET_ID',
    MASTER_SPREADSHEET_ID: 'CENTRAL_AGF_MASTER_SPREADSHEET_ID',
    PROCESSING_SPREADSHEET_ID: 'CENTRAL_AGF_PROCESSING_SPREADSHEET_ID'
  }),
  FILE_NAMES: Object.freeze({
    QUERY: 'CONSULTA_HISTORICA_POSTAGENS',
    CONTROL: 'CONTROLE_CARGAS_POSTAGENS',
    MASTER: 'CADASTRO_MESTRE_CLIENTES',
    PROCESSING: 'PROCESSAMENTO_POSTAGENS_CORREIOS'
  }),
  SHEETS: Object.freeze({
    PANEL: '00_PAINEL',
    PARAMS: '01_PARAMETROS',
    CLIENTS: '02_CLIENTES',
    POSTS: '03_POSTAGENS',
    AUDIT_CENTER_LOCAL: '04_AUDITORIA_CENTRO_LOCAL',
    DIVERGENCES: '05_DIVERGENCIAS',
    PARTITION_CATALOG_VIEW: '06_CATALOGO_PARTICOES',
    HOMOLOGATION: '07_HOMOLOGACAO',
    READ_FIRST: '08_LEIA_PRIMEIRO',
    SOURCE_RECONCILIATION: '09_RECONCILIACAO_FONTES',
    PARTITION_CATALOG_SOURCE: '03_PARTICOES',
    FACTS: '01_FATOS',
    PROCESSING_CONTRACTS: '02_CONTRATOS',
    MASTER_CLIENTS: '01_CLIENTES_MASTER',
    MASTER_SENDER_ALIASES: '02_ALIASES_NOME_REMETENTE',
    MASTER_IDENTITY_DIAGNOSTIC: '13_DIAGNOSTICO_IDENTIDADE',
    MASTER_MIGRATION_PREVIEW: '14_PREVIA_MIGRACAO_CLIENTES',
    MASTER_IDENTITY_REVIEW: '15_FILA_REVISAO_IDENTIDADE',
    MASTER_IDENTITY_SUMMARY: '16_RESUMO_IDENTIDADE',
    MASTER_IDENTITY_ASSISTED_REVIEW: '17_FILA_REVISAO_ASSISTIDA',
    MASTER_SAFE_MIGRATION_BATCH: '18_LOTE_SEGURO_CLIENTES',
    MASTER_SAFE_MIGRATION_CONFLICTS: '19_CONFLITOS_LOTE_SEGURO',
    MASTER_SAFE_MIGRATION_SUMMARY: '20_RESUMO_LOTE_SEGURO',
    MASTER_CLIENT_ID_PROPOSAL: '21_PROPOSTA_CLIENTES_MASTER',
    MASTER_CLIENT_ID_PROPOSAL_CONFLICTS: '22_CONFLITOS_PROPOSTA_ID',
    MASTER_CLIENT_ID_PROPOSAL_SUMMARY: '23_RESUMO_PROPOSTA_ID',
    MASTER_QUALITY_AUDIT: '24_AUDITORIA_QUALIDADE_MASTER',
    MASTER_QUALITY_SUMMARY: '25_RESUMO_QUALIDADE_MASTER'
  }),
  QUERY: Object.freeze({
    WRITE_CHUNK_ROWS: 2500,
    HARD_MAX_ROWS: 500000,
    DEFAULT_MODE: 'POSTAGENS',
    ALLOW_ORIGIN_FALLBACK: true
  }),
  AUDIT: Object.freeze({
    BILLING_TOLERANCE: 0.01,
    SRO_REGEX: /^[A-Z]{2}\d{9}BR$/,
    SPECIAL_OBJECTS: Object.freeze(['SEM_REGISTRO', 'PRODUTO_ECT']),
    SOURCE_OK_STATUS: 'OK_FONTE'
  }),
  IDENTITY: Object.freeze({
    AGF_COUNTER_NAME: 'BALCÃO',
    METRO_SHARED_NAME: 'GAS SHOPPING METRO',
    PLACEHOLDER_NAMES: Object.freeze([
      'BALCÃO',
      'REMETENTE',
      'CLIENTE',
      'CONSUMIDOR',
      'SEM NOME',
      'NÃO INFORMADO',
      'NAO INFORMADO',
      'GAS SHOPPING METRO',
      'GAS SHOPPING CENTRO FASHION',
      '-',
      '.'
    ])
  })
});