/**
 * AGF SUPERFRETE — 30_SF_CFG.gs
 * Configuração e modelo de dados do módulo SuperFrete.
 *
 * Etapa 1: estrutura de planilha, autenticação básica, conta corrente,
 * carteira SuperFrete, DC-e/DACE e placeholders seguros para integração.
 *
 * Importante:
 * - Não altera o /app CWS atual.
 * - Não altera o /balcao.
 * - Token SuperFrete deve ficar em PropertiesService, não na planilha.
 */

const SF = {
  APP_NAME: 'AGF SuperFrete',
  VERSION: '0.8.0-cliente-v1',

  SESSION_PREFIX: 'AGF_SF_SES_',
  SESSION_TTL_SEC: 60 * 60 * 12,

  PROPERTIES: {
    SUPERFRETE_TOKEN_SANDBOX: 'SF_SUPERFRETE_TOKEN_SANDBOX',
    SUPERFRETE_TOKEN_PRODUCAO: 'SF_SUPERFRETE_TOKEN_PRODUCAO',
    INFINITEPAY_TOKEN: 'SF_INFINITEPAY_TOKEN'
  },

  SHEETS: {
    USUARIOS: 'SF_USUARIOS',
    CLIENTES: 'SF_CLIENTES',
    REMETENTES: 'SF_REMETENTES',
    CONTAS: 'SF_CONTAS_CLIENTES',
    LANC_CLIENTES: 'SF_LANCAMENTOS_CLIENTES',
    CARTEIRA_SF: 'SF_CARTEIRA_SUPERFRETE',
    ETIQUETAS: 'SF_ETIQUETAS',
    DECLARACAO_ITENS: 'SF_DECLARACAO_ITENS',
    DCE_DOCUMENTOS: 'SF_DCE_DOCUMENTOS',
    COBRANCAS_PIX: 'SF_COBRANCAS_PIX',
    COBRANCA_ITENS: 'SF_COBRANCA_ITENS',
    PAGAMENTOS: 'SF_PAGAMENTOS',
    CONFIG: 'SF_CONFIG',
    LOGS: 'SF_LOGS',
    LISTAS: 'SF_LISTAS'
  },

  HEADERS: {
    SF_USUARIOS: ['USUARIO_ID','TIPO_USUARIO','CLIENTE_ID','NOME','LOGIN','SENHA_HASH','STATUS','PERMISSOES','ULTIMO_LOGIN','CRIADO_EM','ATUALIZADO_EM'],
    SF_CLIENTES: ['CLIENTE_ID','STATUS','NOME_EXIBICAO','RAZAO_SOCIAL','DOCUMENTO','EMAIL','TELEFONE','LOGO_DRIVE_ID','LOGO_URL','OBS_INTERNA','CRIADO_EM','ATUALIZADO_EM'],
    SF_REMETENTES: ['REMETENTE_ID','CLIENTE_ID','STATUS','NOME_REMETENTE','RAZAO_SOCIAL','CNPJ_CPF','EMAIL','TELEFONE','CEP','ENDERECO','NUMERO','COMPLEMENTO','BAIRRO','CIDADE','UF','PADRAO','CRIADO_EM','ATUALIZADO_EM'],
    SF_CONTAS_CLIENTES: ['CLIENTE_ID','LIMITE_CREDITO','SALDO_CONTA','VALOR_RESERVADO','DISPONIVEL_EMISSAO','STATUS_CREDITO','BLOQUEAR_EMISSAO','ATUALIZADO_EM'],
    SF_LANCAMENTOS_CLIENTES: ['LANCAMENTO_ID','CLIENTE_ID','TIPO','VALOR','SINAL','SALDO_ANTES','SALDO_DEPOIS','ORDER_ID_AGF','COBRANCA_ID','PAGAMENTO_ID','OPERADOR_ID','ORIGEM','MOTIVO','CRIADO_EM'],
    SF_CARTEIRA_SUPERFRETE: ['LANCAMENTO_ID','TIPO','VALOR','SINAL','SALDO_ANTES','SALDO_DEPOIS','ORDER_ID_AGF','ORDER_ID_SUPERFRETE','OPERADOR_ID','REFERENCIA','OBS','CRIADO_EM'],
    SF_ETIQUETAS: ['ORDER_ID_AGF','ORDER_ID_SUPERFRETE','CLIENTE_ID','REMETENTE_ID','OPERADOR_ID','ORIGEM_EMISSAO','STATUS_LOGISTICO','STATUS_FINANCEIRO','SERVICO','TRANSPORTADORA','TRACKING','VALOR_COTADO','VALOR_RESERVADO','VALOR_REAL_SUPERFRETE','VALOR_COBRADO_CLIENTE','DIFERENCA_COTACAO','COBRANCA_ID','PDF_OFICIAL_URL','PDF_AGF_URL','DCE_STATUS','DCE_CHAVE_ACESSO','DACE_URL','DESTINATARIO_NOME','DESTINATARIO_DOCUMENTO','DESTINATARIO_CEP','DESTINATARIO_ENDERECO','DESTINATARIO_NUMERO','DESTINATARIO_COMPLEMENTO','DESTINATARIO_BAIRRO','DESTINATARIO_CIDADE','DESTINATARIO_UF','PESO','ALTURA','LARGURA','COMPRIMENTO','PAYLOAD_COTACAO_JSON','PAYLOAD_PEDIDO_JSON','RESPONSE_SUPERFRETE_JSON','CRIADO_EM','EMITIDO_EM','CANCELADO_EM'],
    SF_DECLARACAO_ITENS: ['ORDER_ID_AGF','ITEM_SEQ','DESCRICAO','QUANTIDADE','VALOR_UNITARIO','VALOR_TOTAL','UNIDADE','NCM_OPCIONAL','PESO_APROX_G','OBS'],
    SF_DCE_DOCUMENTOS: ['ORDER_ID_AGF','CLIENTE_ID','TIPO_DOCUMENTO','DCE_STATUS','DCE_CHAVE_ACESSO','DACE_URL','DACE_QR_CODE','DACE_PDF_URL','EMITIDO_EM','PAYLOAD_DCE_JSON','RESPONSE_DCE_JSON','OBS_VALIDACAO'],
    SF_COBRANCAS_PIX: ['COBRANCA_ID','CLIENTE_ID','STATUS','VALOR_TOTAL','QTD_ETIQUETAS','TIPO_COBRANCA','PROVEDOR','PROVEDOR_PAYMENT_ID','PROVEDOR_ORDER_NSU','PIX_QR_CODE','PIX_COPIA_COLA','CHECKOUT_URL','VENCIMENTO','CRIADO_POR','ORIGEM','CRIADO_EM','PAGO_EM','CANCELADO_EM','OBS'],
    SF_COBRANCA_ITENS: ['COBRANCA_ID','ORDER_ID_AGF','CLIENTE_ID','VALOR_ITEM','STATUS_ITEM','CRIADO_EM'],
    SF_PAGAMENTOS: ['PAGAMENTO_ID','COBRANCA_ID','CLIENTE_ID','PROVEDOR','VALOR_ESPERADO','VALOR_PAGO','METODO','STATUS','TRANSACTION_ID','RECEIPT_URL','PAGO_EM','CRIADO_EM'],
    SF_CONFIG: ['CHAVE','VALOR','DESCRICAO','ATUALIZADO_EM'],
    SF_LOGS: ['LOG_ID','NIVEL','MODULO','ACAO','CLIENTE_ID','USUARIO_ID','MENSAGEM','PAYLOAD_JSON','CRIADO_EM'],
    SF_LISTAS: ['LISTA','VALOR','DESCRICAO']
  },

  STATUS: {
    ATIVO: 'ATIVO',
    BLOQUEADO: 'BLOQUEADO',
    INATIVO: 'INATIVO'
  },

  DEFAULTS: {
    ADMIN_LOGIN: 'admin',
    // ADMIN_PASSWORD removido: a senha inicial agora é aleatória (ver 31_SF_BOOTSTRAP.js).
    CLIENTE_EXEMPLO_LOGIN: 'cliente.exemplo',
    CLIENTE_EXEMPLO_PASSWORD: 'cliente123',
    LIMITE_CLIENTE_EXEMPLO: 300,
    MARGEM_SEGURANCA_COTACAO: 5
  }
};
