(function(){
'use strict';
const auth=window.AgfAuth,$=(id)=>document.getElementById(id),form=$('userForm'),status=$('formStatus'),list=$('usersList'),meta=$('listMeta');let users=[],apps=[],editingUsername='';const EXTRA_APPS=[{key:'reverso-admin',label:'Admin Reverso',category:'Logística reversa',roles:['admin','manager','user'],defaultEnabled:false},{key:'reverso-coleta',label:'Coleta Reverso',category:'Logística reversa',roles:['admin','manager','user'],defaultEnabled:false},{key:'reverso-expedicao',label:'Expedição Reverso',category:'Logística reversa',roles:['admin','manager','user'],defaultEnabled:false}];function mergeApps(base){const out=Array.isArray(base)?base.slice():[];EXTRA_APPS.forEach((extra)=>{if(!out.some((app)=>app.key===extra.key))out.push(extra);});return out;}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function setStatus(message,error){status.textContent=message||'';status.style.color=error?'#b42318':'#60788d';}
function initPasswordToggles(){document.querySelectorAll('[data-password-toggle]').forEach((button)=>{const input=$(button.dataset.passwordToggle),icon=button.querySelector('.material-symbols-rounded');if(!input||button.dataset.passwordReady==='1')return;button.dataset.passwordReady='1';button.addEventListener('click',()=>{const shouldShow=input.type==='password';input.type=shouldShow?'text':'password';button.setAttribute('aria-pressed',String(shouldShow));button.setAttribute('aria-label',shouldShow?'Ocultar senha':'Mostrar senha');button.setAttribute('title',shouldShow?'Ocultar senha':'Mostrar senha');if(icon)icon.textContent=shouldShow?'visibility_off':'visibility';input.focus({preventScroll:true});});});}
function formatDate(value){if(!value)return 'nunca';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString('pt-BR');}
function roleMeta(role){const map={admin:{label:'Admin',css:'admin'},manager:{label:'Gestor',css:'manager'},user:{label:'Usuário',css:''}};return map[role]||map.user;}
function roleDefaults(role){return {agendaScope:role==='admin'?'ALL':(role==='manager'?'TEAM':'OWN'),canEditClients:role!=='user',canEditProspects:role!=='user',canMoveFunnel:true,canCompleteActivities:true,canViewTeam:role!=='user',canViewIndicators:role!=='user'};}
function appAllowedByRole(app,role){return Array.isArray(app.roles)&&app.roles.indexOf(role)>=0;}
function selectedApps(){return Array.from(document.querySelectorAll('[data-app-check]:checked')).map((input)=>input.value);}
function defaultAppsForRole(role){return apps.filter((app)=>appAllowedByRole(app,role)&&app.defaultEnabled!==false).map((app)=>app.key);}
function renderApps(selected){const role=$('role').value||'user',chosen=Array.isArray(selected)?selected:selectedApps();$('appsGrid').innerHTML=apps.map((app)=>{const enabled=appAllowedByRole(app,role),checked=enabled&&chosen.indexOf(app.key)>=0;return `<label class="app-check ${enabled?'':'disabled'}"><input data-app-check type="checkbox" value="${esc(app.key)}" ${checked?'checked':''} ${enabled?'':'disabled'}><span><strong>${esc(app.label)}</strong><small>${esc(app.category||'')}</small></span></label>`;}).join('')||'<span class="muted-line">Catálogo de aplicativos indisponível.</span>';}
function setCrmOptions(profile,useRoleDefaults){const role=$('role').value||'user',defaults=roleDefaults(role),crm=profile||{};$('crmLinked').checked=Boolean(crm.linked);$('crmAgendaScope').value=crm.agendaScope||(useRoleDefaults?defaults.agendaScope:'OWN');$('crmCanEditClients').checked=crm.canEditClients!=null?Boolean(crm.canEditClients):defaults.canEditClients;$('crmCanEditProspects').checked=crm.canEditProspects!=null?Boolean(crm.canEditProspects):defaults.canEditProspects;$('crmCanMoveFunnel').checked=crm.canMoveFunnel!=null?Boolean(crm.canMoveFunnel):defaults.canMoveFunnel;$('crmCanCompleteActivities').checked=crm.canCompleteActivities!=null?Boolean(crm.canCompleteActivities):defaults.canCompleteActivities;$('crmCanViewTeam').checked=crm.canViewTeam!=null?Boolean(crm.canViewTeam):defaults.canViewTeam;$('crmCanViewIndicators').checked=crm.canViewIndicators!=null?Boolean(crm.canViewIndicators):defaults.canViewIndicators;toggleCrmOptions();}
function getCrmPayload(){return {linked:$('crmLinked').checked,agendaScope:$('crmAgendaScope').value,canEditClients:$('crmCanEditClients').checked,canEditProspects:$('crmCanEditProspects').checked,canMoveFunnel:$('crmCanMoveFunnel').checked,canCompleteActivities:$('crmCanCompleteActivities').checked,canViewTeam:$('crmCanViewTeam').checked,canViewIndicators:$('crmCanViewIndicators').checked};}
function toggleCrmOptions(){$('crmOptions').classList.toggle('hide',!$('crmLinked').checked);}
function clearForm(clearStatus){editingUsername='';form.reset();$('active').checked=true;$('role').value='user';$('username').readOnly=false;$('formTitle').textContent='Novo usuário';renderApps(defaultAppsForRole('user'));setCrmOptions({},true);if(clearStatus!==false)setStatus('');}
function render(){meta.textContent=users.length+' usuário'+(users.length===1?'':'s');if(!users.length){list.innerHTML='<div class="empty-list">Nenhum usuário cadastrado.</div>';return;}list.innerHTML=users.map((user)=>{const role=roleMeta(user.role),crm=user.crm||{},appLabels=(user.apps||[]).map((key)=>{const found=apps.find((app)=>app.key===key);return found?found.label:key;});return `<article class="user-row"><div class="user-main"><div class="user-head"><strong>${esc(user.displayName||user.username)}</strong><span class="user-login">${esc(user.username)}</span><span class="user-badge ${role.css}">${role.label}</span>${user.active?'':'<span class="user-badge inactive">Inativo</span>'}${crm.linked?'<span class="user-badge crm">CRM</span>':''}</div><div class="user-meta">Último login: ${esc(formatDate(user.lastLoginAt))}</div><div class="user-apps">${appLabels.map((name)=>`<span>${esc(name)}</span>`).join('')||'<em>Nenhum aplicativo selecionado</em>'}</div></div><div class="user-actions"><button class="row-action" type="button" data-action="edit" data-user="${esc(user.username)}" title="Editar"><span class="material-symbols-rounded">edit</span></button><button class="row-action" type="button" data-action="toggle" data-user="${esc(user.username)}" title="${user.active?'Desativar':'Ativar'}"><span class="material-symbols-rounded">${user.active?'person_off':'person_check'}</span></button><button class="row-action" type="button" data-action="revoke" data-user="${esc(user.username)}" title="Encerrar sessões"><span class="material-symbols-rounded">logout</span></button></div></article>`;}).join('');}
async function load(){meta.textContent='Atualizando…';try{const response=await auth.adminListUsers();apps=mergeApps(response.apps||[]);users=response.users||[];renderApps(editingUsername?selectedApps():defaultAppsForRole($('role').value||'user'));render();}catch(error){meta.textContent=error.message;setTimeout(()=>auth.redirectToLogin('perfil'),900);}}
function userByName(name){return users.find((item)=>item.username===name);}
function edit(name){const user=userByName(name);if(!user)return;editingUsername=user.username;$('username').value=user.username;$('username').readOnly=true;$('displayName').value=user.displayName||'';$('password').value='';$('role').value=user.role||'user';$('active').checked=Boolean(user.active);$('formTitle').textContent='Editar usuário';renderApps(user.apps||[]);setCrmOptions(user.crm||{},false);window.scrollTo({top:0,behavior:'smooth'});}
async function save(payload,message){setStatus('Salvando…');try{await auth.adminSaveUser(payload);clearForm(false);setStatus(message||'Usuário salvo.');await load();}catch(error){setStatus(error.message,true);}}
form.addEventListener('submit',async(event)=>{event.preventDefault();const payload={username:$('username').value.trim().toLowerCase(),displayName:$('displayName').value.trim(),password:$('password').value,role:$('role').value,active:$('active').checked,apps:selectedApps(),crm:getCrmPayload()};await save(payload,'Usuário salvo. Se havia sessões antigas, elas foram encerradas quando necessário.');});
list.addEventListener('click',async(event)=>{const button=event.target.closest('[data-action]');if(!button)return;const user=userByName(button.dataset.user);if(!user)return;if(button.dataset.action==='edit'){edit(user.username);return;}if(button.dataset.action==='toggle'){if(!confirm((user.active?'Desativar ':'Ativar ')+user.displayName+'?'))return;await save({username:user.username,displayName:user.displayName,password:'',role:user.role,active:!user.active,apps:user.apps||[],crm:user.crm||{}},user.active?'Usuário desativado.':'Usuário ativado.');return;}if(button.dataset.action==='revoke'){if(!confirm('Encerrar todas as sessões abertas de '+user.displayName+'?'))return;setStatus('Encerrando sessões…');try{const response=await auth.adminRevokeSessions(user.username);setStatus((response.revoked||0)+' sessão(ões) encerrada(s).');}catch(error){setStatus(error.message,true);}}});
$('role').addEventListener('change',()=>{const role=$('role').value||'user';renderApps(editingUsername?selectedApps():defaultAppsForRole(role));setCrmOptions(editingUsername?getCrmPayload():{},true);});$('crmLinked').addEventListener('change',toggleCrmOptions);$('clearButton').addEventListener('click',clearForm);$('reloadButton').addEventListener('click',load);$('purgeButton').addEventListener('click',async()=>{setStatus('Limpando sessões antigas…');try{const response=await auth.adminPurgeSessions();setStatus((response.removed||0)+' sessão(ões) antiga(s) removida(s).');}catch(error){setStatus(error.message,true);}});$('syncCrmButton').addEventListener('click',async()=>{setStatus('Sincronizando responsáveis CRM…');try{const response=await auth.adminSyncCrmResponsaveis();setStatus((response.synced||0)+' responsável(is) sincronizado(s) com o CRM.');}catch(error){setStatus(error.message,true);}});$('logoutButton').addEventListener('click',async()=>{await auth.logout();auth.redirectToLogin('login');});
initPasswordToggles();clearForm();load();
})();
