# Conector AGF - Shopify
# Plataforma Digital AGF
#
# App standalone.
# Interface principal em minhaagenciaonline.com.br/shopify.
# Backend hospedado separadamente no Cloudflare.
#
# API travada na ultima versao estavel validada em 22/09/2026.

client_id = "61622c164f2f40b89f889aa087e0799b"
name = "Conector AGF"

application_url = "https://shopify.dev/apps/default-app-home"

embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/shopify/auth/callback"
]
