[build]
  publish = "frontend"

[dev]
  publish = "frontend"

[[redirects]]
  from = "/dce"
  to = "https://agf-dce-facil.netlify.app"
  status = 302
  force = true

[[redirects]]
  from = "/dce/*"
  to = "https://agf-dce-facil.netlify.app/:splat"
  status = 302
  force = true
