-- CRM inteiro no D1 (sem planilha e sem Apps Script). Nomes de coluna iguais aos das abas antigas,
-- para o front receber exatamente os mesmos campos. Dados comecam do zero; configuracoes vem dos seeds do codigo antigo.
DROP TABLE IF EXISTS crm_id_legado;

-- ============ configuracao
CREATE TABLE IF NOT EXISTS crm_funis (FUNIL_ID TEXT PRIMARY KEY, NOME_EXIBICAO TEXT NOT NULL DEFAULT '', TIPO_ENTIDADE TEXT NOT NULL DEFAULT '',
  ATIVO TEXT NOT NULL DEFAULT 'SIM', MAX_COLUNAS_VISIVEIS INTEGER NOT NULL DEFAULT 6, ORDEM INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS crm_etapas (ETAPA_ID TEXT PRIMARY KEY, FUNIL_ID TEXT NOT NULL, NOME_EXIBICAO TEXT NOT NULL DEFAULT '', ORDEM INTEGER NOT NULL DEFAULT 0,
  COR TEXT NOT NULL DEFAULT '', ICONE TEXT NOT NULL DEFAULT '', TIPO_ETAPA TEXT NOT NULL DEFAULT 'ABERTA', EXIBE_KANBAN TEXT NOT NULL DEFAULT 'SIM',
  STATUS_FINAL TEXT NOT NULL DEFAULT 'NAO', ATIVA TEXT NOT NULL DEFAULT 'SIM');
CREATE TABLE IF NOT EXISTS crm_tipos_atividade (TIPO_ATIVIDADE_ID TEXT PRIMARY KEY, NOME_EXIBICAO TEXT NOT NULL DEFAULT '', CATEGORIA TEXT NOT NULL DEFAULT '',
  ICONE TEXT NOT NULL DEFAULT '', COR TEXT NOT NULL DEFAULT '', DURACAO_PADRAO_MIN INTEGER NOT NULL DEFAULT 30, USA_BLOCO TEXT NOT NULL DEFAULT 'NAO',
  PERMITE_HORARIO_LIVRE TEXT NOT NULL DEFAULT 'SIM', EXIGE_RESULTADO TEXT NOT NULL DEFAULT 'SIM', ACEITA_MIDIA TEXT NOT NULL DEFAULT 'SIM',
  APLICA_PROSPECT TEXT NOT NULL DEFAULT 'SIM', APLICA_CLIENTE TEXT NOT NULL DEFAULT 'SIM', ATIVA TEXT NOT NULL DEFAULT 'SIM', ORDEM INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS crm_resultados (RESULTADO_ID TEXT PRIMARY KEY, TIPO_ATIVIDADE_ID TEXT NOT NULL DEFAULT 'TODOS', NOME_EXIBICAO TEXT NOT NULL DEFAULT '',
  ATIVA TEXT NOT NULL DEFAULT 'SIM', ORDEM INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS crm_transicoes (ID INTEGER PRIMARY KEY AUTOINCREMENT, FUNIL_ID TEXT NOT NULL, ETAPA_ORIGEM_ID TEXT NOT NULL DEFAULT '*',
  RESULTADO_ID TEXT NOT NULL, ETAPA_DESTINO_ID TEXT NOT NULL DEFAULT '', FOLLOWUP_DIAS_JORNADA INTEGER NOT NULL DEFAULT 0,
  STATUS_TRATATIVA_DESTINO TEXT NOT NULL DEFAULT '', ATIVA_JORNADA TEXT NOT NULL DEFAULT 'SIM', DESCRICAO_JORNADA TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS crm_transicoes_legado (RESULTADO TEXT PRIMARY KEY, ATIVA TEXT NOT NULL DEFAULT 'SIM', NOVO_STATUS TEXT NOT NULL DEFAULT '',
  PROXIMA_ACAO TEXT NOT NULL DEFAULT '', DIAS_FOLLOWUP INTEGER NOT NULL DEFAULT 0, NOVA_ACAO_FUNIL TEXT NOT NULL DEFAULT '', DESCRICAO TEXT NOT NULL DEFAULT '',
  ORDEM INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS crm_segmentos (SEGMENTO_ID TEXT PRIMARY KEY, NOME_EXIBICAO TEXT NOT NULL, ATIVO TEXT NOT NULL DEFAULT 'SIM', ORDEM INTEGER NOT NULL DEFAULT 999);
CREATE TABLE IF NOT EXISTS crm_locais (LOCAL_ID TEXT PRIMARY KEY, NOME_EXIBICAO TEXT NOT NULL, ORDEM INTEGER NOT NULL DEFAULT 999, ATIVO TEXT NOT NULL DEFAULT 'SIM',
  TIPO TEXT NOT NULL DEFAULT 'PONTO', OBS TEXT NOT NULL DEFAULT '', EXIBIR_EM TEXT NOT NULL DEFAULT 'CRM');
CREATE TABLE IF NOT EXISTS crm_listas (LISTA TEXT NOT NULL, CODIGO TEXT NOT NULL, NOME_EXIBICAO TEXT NOT NULL DEFAULT '', ORDEM INTEGER NOT NULL DEFAULT 0,
  ATIVO TEXT NOT NULL DEFAULT 'SIM', PRIMARY KEY (LISTA, CODIGO));
CREATE TABLE IF NOT EXISTS crm_blocos (BLOCO_ID TEXT PRIMARY KEY, ORDEM INTEGER NOT NULL DEFAULT 0, HORA_INICIO TEXT NOT NULL DEFAULT '', HORA_FIM TEXT NOT NULL DEFAULT '',
  NOME_BLOCO TEXT NOT NULL DEFAULT '', TIPO_ATIVIDADE TEXT NOT NULL DEFAULT '', COR TEXT NOT NULL DEFAULT '', ATIVO TEXT NOT NULL DEFAULT 'SIM',
  PERMITE_AGENDAMENTO TEXT NOT NULL DEFAULT 'SIM', COR_PADRAO TEXT NOT NULL DEFAULT '', OBS TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS crm_midias (CODIGO_MIDIA TEXT PRIMARY KEY, ACAO TEXT NOT NULL DEFAULT '', SUBCATEGORIA TEXT NOT NULL DEFAULT '', NOME_MIDIA TEXT NOT NULL DEFAULT '',
  TIPO TEXT NOT NULL DEFAULT '', LINK TEXT NOT NULL DEFAULT '', QUANDO_USAR TEXT NOT NULL DEFAULT '', ATIVA TEXT NOT NULL DEFAULT 'SIM');
-- espelho dos usuarios vinculados ao CRM no cadastro de usuarios (AGF_AUTH); atualizado pelo proprio Worker
CREATE TABLE IF NOT EXISTS crm_responsaveis (RESPONSAVEL_ID TEXT PRIMARY KEY, USERNAME TEXT NOT NULL DEFAULT '', DISPLAY_NAME TEXT NOT NULL DEFAULT '',
  ROLE TEXT NOT NULL DEFAULT '', USER_ACTIVE TEXT NOT NULL DEFAULT 'SIM', CRM_LINKED TEXT NOT NULL DEFAULT 'SIM', AGENDA_SCOPE TEXT NOT NULL DEFAULT 'OWN',
  CAN_EDIT_CLIENTS TEXT NOT NULL DEFAULT 'NAO', CAN_EDIT_PROSPECTS TEXT NOT NULL DEFAULT 'NAO', CAN_MOVE_FUNNEL TEXT NOT NULL DEFAULT 'SIM',
  CAN_COMPLETE_ACTIVITIES TEXT NOT NULL DEFAULT 'SIM', CAN_VIEW_TEAM TEXT NOT NULL DEFAULT 'NAO', CAN_VIEW_INDICATORS TEXT NOT NULL DEFAULT 'NAO',
  UPDATED_AT TEXT NOT NULL DEFAULT '', LOCAIS TEXT NOT NULL DEFAULT '');

-- ============ dados
-- Cadastro manual do cliente. Cliente do Visao 360 (ORIGEM ATENDE) usa o ID do Cadastro v2; cliente criado no CRM (ORIGEM MANUAL) usa CLI_M_xxxxxxxx.
-- Coluna NULL = sem valor manual (vale o calculado); '' = limpo pelo usuario.
CREATE TABLE IF NOT EXISTS crm_cadastro (CLIENTE_ID TEXT PRIMARY KEY, ORIGEM TEXT NOT NULL DEFAULT 'ATENDE',
  NOME_REMETENTE_BASE TEXT, CLIENTE TEXT, NOME_FANTASIA TEXT, RAZAO_SOCIAL TEXT, CNPJ_CPF TEXT, PESSOA_CONTATO TEXT, WHATSAPP TEXT, TELEFONE TEXT, EMAIL TEXT,
  ENDERECO TEXT, NUMERO TEXT, COMPLEMENTO TEXT, BAIRRO TEXT, CEP TEXT, CIDADE TEXT, UF TEXT, LOCAL_PADRAO TEXT, SEGMENTO_PREDOMINANTE TEXT,
  NUMERO_CONTRATO TEXT, CARTAO_POSTAGEM TEXT, STATUS_COMERCIAL TEXT, OBSERVACOES TEXT, ULTIMA_VISITA TEXT, ULTIMO_RESULTADO_VISITA TEXT,
  CHECKLIST_ULTIMA_VISITA_ID TEXT, DATA_PROXIMO_FOLLOWUP TEXT, PROXIMA_ACAO_MANUAL TEXT, ACAO_ATUAL TEXT, MIDIA TEXT, LINK_MIDIA_DIRETO TEXT,
  RESPONSAVEL_CARTEIRA TEXT, RESPONSAVEL_ID TEXT, STATUS_CADASTRO TEXT, TRATATIVA_ATIVA_ID TEXT, ULTIMA_ATIVIDADE_ID TEXT, PROXIMA_ATIVIDADE_EM TEXT,
  CRIADO_EM TEXT NOT NULL DEFAULT '', ATUALIZADO_EM TEXT NOT NULL DEFAULT '', ATUALIZADO_POR TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS idx_crm_cadastro_origem ON crm_cadastro(ORIGEM);

CREATE TABLE IF NOT EXISTS crm_prospects (PROSPECT_ID TEXT PRIMARY KEY, CLIENTE TEXT NOT NULL DEFAULT '', LOCAL TEXT NOT NULL DEFAULT '', SEGMENTO TEXT NOT NULL DEFAULT '',
  NOME_FANTASIA TEXT NOT NULL DEFAULT '', RAZAO_SOCIAL TEXT NOT NULL DEFAULT '', CNPJ_CPF TEXT NOT NULL DEFAULT '', ATIVIDADE_ECONOMICA TEXT NOT NULL DEFAULT '',
  ENDERECO TEXT NOT NULL DEFAULT '', NUMERO TEXT NOT NULL DEFAULT '', COMPLEMENTO TEXT NOT NULL DEFAULT '', BAIRRO TEXT NOT NULL DEFAULT '', CIDADE TEXT NOT NULL DEFAULT '',
  UF TEXT NOT NULL DEFAULT '', CEP TEXT NOT NULL DEFAULT '', MAPS_URL TEXT NOT NULL DEFAULT '', CONTATO TEXT NOT NULL DEFAULT '', CARGO TEXT NOT NULL DEFAULT '',
  WHATSAPP TEXT NOT NULL DEFAULT '', TELEFONE_2 TEXT NOT NULL DEFAULT '', EMAIL TEXT NOT NULL DEFAULT '', INSTAGRAM TEXT NOT NULL DEFAULT '', PERFIL TEXT NOT NULL DEFAULT '',
  POTENCIAL TEXT NOT NULL DEFAULT '', PRIORIDADE TEXT NOT NULL DEFAULT '', STATUS_PROSPECT TEXT NOT NULL DEFAULT '', ETAPA_FUNIL TEXT NOT NULL DEFAULT '',
  RESPONSAVEL TEXT NOT NULL DEFAULT '', ORIGEM_LEAD TEXT NOT NULL DEFAULT '', CANAL_ENVIO_ATUAL TEXT NOT NULL DEFAULT '', PARCEIRO_PRINCIPAL TEXT NOT NULL DEFAULT '',
  USA_INTERMEDIADOR TEXT NOT NULL DEFAULT '', INTERMEDIADOR_QUAL TEXT NOT NULL DEFAULT '', ATENDE_SACOLEIRAS_EXCURSAO TEXT NOT NULL DEFAULT '',
  DOR_PRINCIPAL TEXT NOT NULL DEFAULT '', OPORTUNIDADE_PRINCIPAL TEXT NOT NULL DEFAULT '', DATA_CADASTRO TEXT NOT NULL DEFAULT '', ULTIMO_CONTATO TEXT NOT NULL DEFAULT '',
  ULTIMO_RESULTADO_VISITA TEXT NOT NULL DEFAULT '', DATA_PROXIMO_FOLLOWUP TEXT NOT NULL DEFAULT '', PROXIMA_ACAO TEXT NOT NULL DEFAULT '',
  CHECKLIST_ULTIMA_VISITA_ID TEXT NOT NULL DEFAULT '', CANAL_PREFERENCIAL TEXT NOT NULL DEFAULT '', ABORDAGEM_INICIAL TEXT NOT NULL DEFAULT '',
  OBJECAO_PRINCIPAL TEXT NOT NULL DEFAULT '', TEM_INTERESSE TEXT NOT NULL DEFAULT '', SCORE TEXT NOT NULL DEFAULT '', OBS TEXT NOT NULL DEFAULT '',
  UPDATED_AT TEXT NOT NULL DEFAULT '', CLIENTE_ID_CONVERTIDO TEXT NOT NULL DEFAULT '', CLIENTE_NOME_CONVERTIDO TEXT NOT NULL DEFAULT '', TIPO_CONVERSAO TEXT NOT NULL DEFAULT '',
  DATA_CONVERSAO TEXT NOT NULL DEFAULT '', MATCH_STATUS TEXT NOT NULL DEFAULT '', OBS_CONVERSAO TEXT NOT NULL DEFAULT '', FREQUENCIA_ENVIO TEXT NOT NULL DEFAULT '',
  VOLUME_MEDIO TEXT NOT NULL DEFAULT '', JA_POSTA_CORREIOS TEXT NOT NULL DEFAULT '', TEM_CONTRATO_CORREIOS TEXT NOT NULL DEFAULT '', TEM_CARTAO_POSTAGEM TEXT NOT NULL DEFAULT '',
  CANAL_VENDA TEXT NOT NULL DEFAULT '', RESPONSAVEL_ID TEXT NOT NULL DEFAULT '', TRATATIVA_ATIVA_ID TEXT NOT NULL DEFAULT '', ULTIMA_ATIVIDADE_ID TEXT NOT NULL DEFAULT '',
  PROXIMA_ATIVIDADE_EM TEXT NOT NULL DEFAULT '');

CREATE TABLE IF NOT EXISTS crm_tratativas (TRATATIVA_ID TEXT PRIMARY KEY, TIPO_ENTIDADE TEXT NOT NULL, ENTIDADE_ID TEXT NOT NULL, FUNIL_ID TEXT NOT NULL,
  ETAPA_ID TEXT NOT NULL, STATUS_TRATATIVA TEXT NOT NULL DEFAULT 'ABERTA', ORIGEM TEXT NOT NULL DEFAULT '', ACAO_ENGINE_SNAPSHOT TEXT NOT NULL DEFAULT '',
  SUB_ACAO_SNAPSHOT TEXT NOT NULL DEFAULT '', PRIORIDADE_SNAPSHOT TEXT NOT NULL DEFAULT '', RESPONSAVEL_ID TEXT NOT NULL DEFAULT '', ABERTA_EM TEXT NOT NULL DEFAULT '',
  ETAPA_ATUALIZADA_EM TEXT NOT NULL DEFAULT '', PROXIMO_FOLLOWUP_EM TEXT NOT NULL DEFAULT '', ENCERRADA_EM TEXT NOT NULL DEFAULT '',
  MOTIVO_ENCERRAMENTO TEXT NOT NULL DEFAULT '', UPDATED_BY TEXT NOT NULL DEFAULT '', ATUALIZADO_EM TEXT NOT NULL DEFAULT '', ULTIMA_ATIVIDADE_ID TEXT NOT NULL DEFAULT '',
  PROXIMA_ATIVIDADE_ID TEXT NOT NULL DEFAULT '', MOTIVO_ABERTURA TEXT NOT NULL DEFAULT '', CRIADO_POR TEXT NOT NULL DEFAULT '', FECHADA_POR TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS idx_crm_tratativas_entidade ON crm_tratativas(TIPO_ENTIDADE, ENTIDADE_ID, FUNIL_ID, STATUS_TRATATIVA);

CREATE TABLE IF NOT EXISTS crm_eventos (EVENTO_ID TEXT PRIMARY KEY, DATA_HORA TEXT NOT NULL, ENTIDADE_TIPO TEXT NOT NULL DEFAULT '', ENTIDADE_ID TEXT NOT NULL DEFAULT '',
  TRATATIVA_ID TEXT NOT NULL DEFAULT '', TIPO_EVENTO TEXT NOT NULL, VALOR_ANTERIOR TEXT NOT NULL DEFAULT '', VALOR_NOVO TEXT NOT NULL DEFAULT '',
  RESPONSAVEL_ID TEXT NOT NULL DEFAULT '', ORIGEM TEXT NOT NULL DEFAULT '', METADADOS_JSON TEXT NOT NULL DEFAULT '{}');
CREATE INDEX IF NOT EXISTS idx_crm_eventos_entidade ON crm_eventos(ENTIDADE_ID);

CREATE TABLE IF NOT EXISTS crm_agenda (AGENDA_ID TEXT PRIMARY KEY, TRATATIVA_ID TEXT NOT NULL DEFAULT '', ENTIDADE_TIPO TEXT NOT NULL DEFAULT '', ENTIDADE_ID TEXT NOT NULL DEFAULT '',
  CLIENTE_ID TEXT NOT NULL DEFAULT '', PROSPECT_ID TEXT NOT NULL DEFAULT '', CLIENTE TEXT NOT NULL DEFAULT '', LOCAL TEXT NOT NULL DEFAULT '',
  DATA_PROGRAMADA TEXT NOT NULL DEFAULT '', DIA_SEMANA TEXT NOT NULL DEFAULT '', HORA_PROGRAMADA TEXT NOT NULL DEFAULT '', HORA_FIM_PROGRAMADA TEXT NOT NULL DEFAULT '',
  DURACAO_MIN INTEGER NOT NULL DEFAULT 30, BLOCO_ID TEXT NOT NULL DEFAULT '', TIPO_ATIVIDADE_ID TEXT NOT NULL DEFAULT '', TIPO_ATIVIDADE TEXT NOT NULL DEFAULT '',
  TIPO_COR TEXT NOT NULL DEFAULT '', STATUS_ATIVIDADE TEXT NOT NULL DEFAULT 'PLANEJADO', PRIORIDADE TEXT NOT NULL DEFAULT '', ORDEM_AGENDA INTEGER NOT NULL DEFAULT 999,
  RESULTADO_ID TEXT NOT NULL DEFAULT '', MIDIA_RECOMENDADA_CODIGO TEXT NOT NULL DEFAULT '', LINK_MIDIA_RECOMENDADA TEXT NOT NULL DEFAULT '',
  MIDIA_USADA_CODIGO TEXT NOT NULL DEFAULT '', LINK_MIDIA_USADA TEXT NOT NULL DEFAULT '', RESPONSAVEL_ID TEXT NOT NULL DEFAULT '', RESPONSAVEL TEXT NOT NULL DEFAULT '',
  OBSERVACAO TEXT NOT NULL DEFAULT '', OBS_PLANEJADA TEXT NOT NULL DEFAULT '', OBS_EXECUCAO TEXT NOT NULL DEFAULT '', CHECKLIST_ID TEXT NOT NULL DEFAULT '',
  EXECUTADO_EM TEXT NOT NULL DEFAULT '', CONCLUIDA_EM TEXT NOT NULL DEFAULT '', MOTIVO_CANCELAMENTO TEXT NOT NULL DEFAULT '', REQUEST_ID TEXT,
  CRIADO_EM TEXT NOT NULL DEFAULT '', ATUALIZADO_EM TEXT NOT NULL DEFAULT '', CRIADO_POR TEXT NOT NULL DEFAULT '', ATUALIZADO_POR TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS idx_crm_agenda_data ON crm_agenda(DATA_PROGRAMADA);
CREATE INDEX IF NOT EXISTS idx_crm_agenda_tratativa ON crm_agenda(TRATATIVA_ID);
CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_agenda_request ON crm_agenda(REQUEST_ID) WHERE REQUEST_ID IS NOT NULL AND REQUEST_ID <> '';

CREATE TABLE IF NOT EXISTS crm_interacoes (INTERACAO_ID TEXT PRIMARY KEY, DATA TEXT NOT NULL DEFAULT '', CLIENTE_ID TEXT NOT NULL DEFAULT '', CLIENTE TEXT NOT NULL DEFAULT '',
  TIPO_INTERACAO TEXT NOT NULL DEFAULT '', STATUS TEXT NOT NULL DEFAULT '', RESULTADO TEXT NOT NULL DEFAULT '', OBSERVACAO TEXT NOT NULL DEFAULT '',
  PROXIMA_ACAO TEXT NOT NULL DEFAULT '', RESPONSAVEL TEXT NOT NULL DEFAULT '', CRIADO_EM TEXT NOT NULL DEFAULT '', TRATATIVA_ID TEXT NOT NULL DEFAULT '',
  TIPO_ATIVIDADE_ID TEXT NOT NULL DEFAULT '', RESULTADO_ID TEXT NOT NULL DEFAULT '', RESPONSAVEL_ID TEXT NOT NULL DEFAULT '', ENTIDADE_TIPO TEXT NOT NULL DEFAULT '',
  ENTIDADE_ID TEXT NOT NULL DEFAULT '');

CREATE TABLE IF NOT EXISTS crm_checklists (CHECKLIST_ID TEXT PRIMARY KEY, AGENDA_ID TEXT NOT NULL DEFAULT '', DATA TEXT NOT NULL DEFAULT '', ORIGEM_TIPO TEXT NOT NULL DEFAULT '',
  ORIGEM_ID TEXT NOT NULL DEFAULT '', PROSPECT_ID TEXT NOT NULL DEFAULT '', CLIENTE_MASTER_ID TEXT NOT NULL DEFAULT '', CLIENTE TEXT NOT NULL DEFAULT '',
  RESULTADO_VISITA TEXT NOT NULL DEFAULT '', STATUS_VISITA TEXT NOT NULL DEFAULT '', POSTAGEM_COMO_CHEGA TEXT NOT NULL DEFAULT '', ORIGEM_POSTAGEM TEXT NOT NULL DEFAULT '',
  CANAIS_VENDA TEXT NOT NULL DEFAULT '', POSTA_COM_QUEM TEXT NOT NULL DEFAULT '', DOR_PRINCIPAL TEXT NOT NULL DEFAULT '', OPORTUNIDADE_PRINCIPAL TEXT NOT NULL DEFAULT '',
  NIVEL_ESTEIRA TEXT NOT NULL DEFAULT '', ENTRADA_SUGERIDA TEXT NOT NULL DEFAULT '', POTENCIAL_AUTOMACAO TEXT NOT NULL DEFAULT '', CANAL_ENVIO_ATUAL TEXT NOT NULL DEFAULT '',
  FREQUENCIA_ENVIO TEXT NOT NULL DEFAULT '', VOLUME_MEDIO TEXT NOT NULL DEFAULT '', JA_POSTA_CORREIOS TEXT NOT NULL DEFAULT '', TEM_CONTRATO_CORREIOS TEXT NOT NULL DEFAULT '',
  TEM_CARTAO_POSTAGEM TEXT NOT NULL DEFAULT '', USA_INTERMEDIADOR TEXT NOT NULL DEFAULT '', INTERMEDIADOR_QUAL TEXT NOT NULL DEFAULT '', PARCEIRO_PRINCIPAL TEXT NOT NULL DEFAULT '',
  CANAL_VENDA TEXT NOT NULL DEFAULT '', ATENDE_SACOLEIRAS_EXCURSAO TEXT NOT NULL DEFAULT '', OBSERVACAO_CURTA TEXT NOT NULL DEFAULT '', RESPONSAVEL TEXT NOT NULL DEFAULT '',
  CRIADO_EM TEXT NOT NULL DEFAULT '', TRATATIVA_ID TEXT NOT NULL DEFAULT '', TIPO_ATIVIDADE_ID TEXT NOT NULL DEFAULT '', RESULTADO_ID TEXT NOT NULL DEFAULT '',
  RESPONSAVEL_ID TEXT NOT NULL DEFAULT '', REQUEST_ID TEXT, ATUALIZADO_EM TEXT NOT NULL DEFAULT '', DIAG_SOLICITACAO_RETIRADA TEXT NOT NULL DEFAULT '',
  DIAG_PORTAL_RETIRADA TEXT NOT NULL DEFAULT '', DIAG_USA_RETIRADA_CORREIOS TEXT NOT NULL DEFAULT '', DIAG_INTERESSE_RETIRADA TEXT NOT NULL DEFAULT '',
  AGENCIA_COLETA TEXT NOT NULL DEFAULT '');
CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_checklists_request ON crm_checklists(REQUEST_ID) WHERE REQUEST_ID IS NOT NULL AND REQUEST_ID <> '';

CREATE TABLE IF NOT EXISTS crm_anotacoes (ANOTACAO_ID TEXT PRIMARY KEY, DATA_HORA TEXT NOT NULL, ENTIDADE_TIPO TEXT NOT NULL, ENTIDADE_ID TEXT NOT NULL,
  TRATATIVA_ID TEXT NOT NULL DEFAULT '', AGENDA_ID TEXT NOT NULL DEFAULT '', TEXTO TEXT NOT NULL, RESPONSAVEL_ID TEXT NOT NULL DEFAULT '',
  RESPONSAVEL_NOME TEXT NOT NULL DEFAULT '', ORIGEM TEXT NOT NULL DEFAULT 'CRM_PORTAL', REQUEST_ID TEXT);
CREATE INDEX IF NOT EXISTS idx_crm_anotacoes_entidade ON crm_anotacoes(ENTIDADE_TIPO, ENTIDADE_ID);
CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_anotacoes_request ON crm_anotacoes(REQUEST_ID) WHERE REQUEST_ID IS NOT NULL AND REQUEST_ID <> '';

INSERT OR IGNORE INTO cid_estado(chave, valor) VALUES ('crm_data_rev', '1'), ('crm_config_rev', '1');

-- ============ seeds (valores do codigo antigo do CRM)
INSERT OR IGNORE INTO crm_funis VALUES
 ('FUNIL_PROSPECTS','Jornada de Prospects','PROSPECT','SIM',6,1),
 ('FUNIL_CLIENTES','Jornada de Clientes','CLIENTE','SIM',6,2);
INSERT OR IGNORE INTO crm_etapas VALUES
 ('P_NOVO','FUNIL_PROSPECTS','Novo lead',1,'#E2E8F0','person_add','ABERTA','SIM','NAO','SIM'),
 ('P_QUALIFICADO','FUNIL_PROSPECTS','Qualificado',2,'#DBEAFE','verified','ABERTA','SIM','NAO','SIM'),
 ('P_CONTATO','FUNIL_PROSPECTS','Contato estabelecido',3,'#EDE9FE','forum','ABERTA','SIM','NAO','SIM'),
 ('P_OPORTUNIDADE','FUNIL_PROSPECTS','Oportunidade identificada',4,'#FEF3C7','lightbulb','ABERTA','SIM','NAO','SIM'),
 ('P_NEGOCIACAO','FUNIL_PROSPECTS','Em negociação',5,'#FFEDD5','handshake','ABERTA','SIM','NAO','SIM'),
 ('P_CONVERTIDO','FUNIL_PROSPECTS','Convertido',6,'#DCFCE7','check_circle','GANHA','SIM','SIM','SIM'),
 ('P_NUTRICAO','FUNIL_PROSPECTS','Nutrição',90,'#F1F5F9','schedule','PAUSADA','NAO','NAO','SIM'),
 ('P_PERDIDO','FUNIL_PROSPECTS','Perdido',91,'#FEE2E2','cancel','PERDIDA','NAO','SIM','SIM'),
 ('C_SINALIZADO','FUNIL_CLIENTES','Sinalizado',1,'#E2E8F0','flag','ABERTA','SIM','NAO','SIM'),
 ('C_TRATATIVA','FUNIL_CLIENTES','Em tratativa',2,'#DBEAFE','forum','ABERTA','SIM','NAO','SIM'),
 ('C_NECESSIDADE','FUNIL_CLIENTES','Necessidade mapeada',3,'#EDE9FE','search','ABERTA','SIM','NAO','SIM'),
 ('C_SOLUCAO','FUNIL_CLIENTES','Solução em andamento',4,'#FEF3C7','construction','ABERTA','SIM','NAO','SIM'),
 ('C_ACOMPANHAMENTO','FUNIL_CLIENTES','Em acompanhamento',5,'#FFEDD5','schedule','ABERTA','SIM','NAO','SIM'),
 ('C_CONCLUIDO','FUNIL_CLIENTES','Concluído',6,'#DCFCE7','check_circle','GANHA','SIM','SIM','SIM'),
 ('C_PAUSADO','FUNIL_CLIENTES','Pausado',90,'#F1F5F9','pause_circle','PAUSADA','NAO','NAO','SIM'),
 ('C_SEM_AVANCO','FUNIL_CLIENTES','Encerrado sem avanço',91,'#FEE2E2','cancel','PERDIDA','NAO','SIM','SIM');
INSERT OR IGNORE INTO crm_tipos_atividade VALUES
 ('ATV_VISITA','Visita presencial','PRESENCIAL','location_on','#F59E0B',120,'SIM','SIM','SIM','SIM','SIM','SIM','SIM',1),
 ('ATV_LIGACAO','Ligação','REMOTO','call','#2563EB',30,'NAO','SIM','SIM','NAO','SIM','SIM','SIM',2),
 ('ATV_WHATSAPP','Enviar WhatsApp','REMOTO','chat','#16A34A',15,'NAO','SIM','SIM','SIM','SIM','SIM','SIM',3),
 ('ATV_EMAIL','Enviar e-mail','REMOTO','mail','#7C3AED',15,'NAO','SIM','SIM','SIM','SIM','SIM','SIM',4),
 ('ATV_REUNIAO_ONLINE','Reunião on-line','REMOTO','videocam','#0F766E',60,'NAO','SIM','SIM','SIM','SIM','SIM','SIM',5),
 ('ATV_PROPOSTA','Enviar proposta','DOCUMENTO','description','#EA580C',30,'NAO','SIM','SIM','SIM','SIM','SIM','SIM',6),
 ('ATV_RETORNO','Retorno','REMOTO','reply','#0284C7',30,'NAO','SIM','SIM','SIM','SIM','SIM','SIM',7),
 ('ATV_TREINAMENTO','Treinamento','PRESENCIAL','school','#9333EA',90,'SIM','SIM','SIM','SIM','NAO','SIM','SIM',8);
INSERT OR IGNORE INTO crm_resultados VALUES
 ('RES_SEM_RESPOSTA','TODOS','Sem resposta','SIM',1), ('RES_REAGENDADO','TODOS','Reagendado','SIM',2),
 ('RES_INTERESSE','TODOS','Demonstrou interesse','SIM',3), ('RES_PROPOSTA_ENVIADA','TODOS','Proposta enviada','SIM',4),
 ('RES_SEM_INTERESSE','TODOS','Sem interesse no momento','SIM',5), ('RES_CONTRATO_FECHADO','TODOS','Contrato fechado','SIM',6),
 ('RES_CLIENTE_RECUPERADO','TODOS','Cliente voltou a postar','SIM',7), ('RES_NAO_ENCONTRADO','ATV_VISITA','Cliente não encontrado','SIM',8),
 ('RES_CONCLUIDO','TODOS','Concluído','SIM',99);
INSERT INTO crm_transicoes(FUNIL_ID, ETAPA_ORIGEM_ID, RESULTADO_ID, ETAPA_DESTINO_ID, FOLLOWUP_DIAS_JORNADA, STATUS_TRATATIVA_DESTINO, ATIVA_JORNADA, DESCRICAO_JORNADA)
 SELECT * FROM (VALUES
 ('FUNIL_PROSPECTS','*','RES_INTERESSE','P_OPORTUNIDADE',2,'ABERTA','SIM','Prospect demonstrou interesse.'),
 ('FUNIL_PROSPECTS','*','RES_PROPOSTA_ENVIADA','P_NEGOCIACAO',3,'ABERTA','SIM','Proposta enviada ao prospect.'),
 ('FUNIL_PROSPECTS','*','RES_CONTRATO_FECHADO','P_CONVERTIDO',0,'CONCLUIDA','SIM','Prospect convertido em cliente.'),
 ('FUNIL_PROSPECTS','*','RES_SEM_INTERESSE','P_PERDIDO',30,'ENCERRADA','SIM','Prospect sem interesse no momento.'),
 ('FUNIL_PROSPECTS','*','RES_SEM_RESPOSTA','',2,'ABERTA','SIM','Manter etapa e criar follow-up.'),
 ('FUNIL_PROSPECTS','*','RES_REAGENDADO','',0,'ABERTA','SIM','Manter etapa após reagendamento.'),
 ('FUNIL_PROSPECTS','*','RES_NAO_ENCONTRADO','',1,'ABERTA','SIM','Nova tentativa de contato.'),
 ('FUNIL_CLIENTES','*','RES_INTERESSE','C_NECESSIDADE',2,'ABERTA','SIM','Necessidade comercial identificada.'),
 ('FUNIL_CLIENTES','*','RES_PROPOSTA_ENVIADA','C_SOLUCAO',3,'ABERTA','SIM','Solução ou proposta em andamento.'),
 ('FUNIL_CLIENTES','*','RES_CONTRATO_FECHADO','C_CONCLUIDO',0,'CONCLUIDA','SIM','Tratativa concluída com contrato.'),
 ('FUNIL_CLIENTES','*','RES_CLIENTE_RECUPERADO','C_CONCLUIDO',0,'CONCLUIDA','SIM','Cliente recuperado.'),
 ('FUNIL_CLIENTES','*','RES_SEM_INTERESSE','C_PAUSADO',30,'PAUSADA','SIM','Pausar e revisar futuramente.'),
 ('FUNIL_CLIENTES','*','RES_SEM_RESPOSTA','C_ACOMPANHAMENTO',7,'ABERTA','SIM','Aguardar retorno e repetir contato.'),
 ('FUNIL_CLIENTES','*','RES_REAGENDADO','',0,'ABERTA','SIM','Manter etapa após reagendamento.'),
 ('FUNIL_CLIENTES','*','RES_NAO_ENCONTRADO','C_TRATATIVA',1,'ABERTA','SIM','Realizar nova tentativa.'),
 ('FUNIL_CLIENTES','*','RES_CONCLUIDO','C_CONCLUIDO',0,'CONCLUIDA','SIM','Tratativa concluída manualmente.'))
 WHERE NOT EXISTS (SELECT 1 FROM crm_transicoes);
INSERT OR IGNORE INTO crm_transicoes_legado VALUES
 ('CONTRATO_FECHADO','SIM','CONTRATO ATIVO','Acompanhar em 30 dias',30,'FIDELIZAR','Cliente assinou contrato - migra para fidelização',1),
 ('PROPOSTA_APRESENTADA','SIM','PROPOSTA PENDENTE','Follow-up da proposta',3,'CONVERTER','Proposta entregue - acompanhar resposta em 3 dias',2),
 ('PROPOSTA_ACEITA','SIM','CONTRATO EM PROCESSO','Enviar contrato para assinatura',2,'CONVERTER','Proposta aceita - formalizar contrato',3),
 ('CLIENTE_INTERESSADO','SIM','EM NEGOCIAÇÃO','Enviar proposta comercial',2,'CONVERTER','Demonstrou interesse - preparar proposta',4),
 ('SEM_INTERESSE','SIM','SEM INTERESSE','Revisitar em 60 dias',60,'MANTER','Não quer agora - manter contato futuro',5),
 ('REAGENDADO','SIM','REAGENDADO','Agendar novo contato',0,'','Cliente pediu para reagendar',6),
 ('NAO_ENCONTRADO','SIM','TENTATIVA S/ CONTATO','Ligar amanhã',1,'','Não estava no local - tentar novamente',7),
 ('CANCELADO','SIM','VISITA CANCELADA','',0,'','Visita cancelada - sem redistribuir',8),
 ('CONCLUIDO','SIM','','',0,'','Genérico - sem mudança automática',9);
INSERT OR IGNORE INTO crm_listas VALUES
 ('POTENCIAL','Alto','Alto',1,'SIM'), ('POTENCIAL','Médio','Médio',2,'SIM'), ('POTENCIAL','Baixo','Baixo',3,'SIM'), ('POTENCIAL','A avaliar','A avaliar',4,'SIM'),
 ('PRIORIDADE','P1','P1 - alta',1,'SIM'), ('PRIORIDADE','P2','P2 - média',2,'SIM'), ('PRIORIDADE','P3','P3 - baixa',3,'SIM'),
 ('ORIGEM_LEAD','Prospecção ativa','Prospecção ativa',1,'SIM'), ('ORIGEM_LEAD','Indicação','Indicação',2,'SIM'), ('ORIGEM_LEAD','WhatsApp','WhatsApp',3,'SIM'),
 ('ORIGEM_LEAD','Instagram','Instagram',4,'SIM'), ('ORIGEM_LEAD','Google/Busca','Google/Busca',5,'SIM'), ('ORIGEM_LEAD','Cliente ativo','Cliente ativo',6,'SIM'),
 ('ORIGEM_LEAD','Parceria','Parceria',7,'SIM'), ('ORIGEM_LEAD','Outro','Outro',8,'SIM'),
 ('STATUS_PROSPECT','NOVO','Novo',1,'SIM'), ('STATUS_PROSPECT','EM ANDAMENTO','Em andamento',2,'SIM'), ('STATUS_PROSPECT','TENTATIVA S/ CONTATO','Tentativa sem contato',3,'SIM'),
 ('STATUS_PROSPECT','REAGENDADO','Reagendado',4,'SIM'), ('STATUS_PROSPECT','VISITA CANCELADA','Visita cancelada',5,'SIM'), ('STATUS_PROSPECT','SEM INTERESSE','Sem interesse',6,'SIM');
INSERT OR IGNORE INTO crm_blocos VALUES
 ('B1',1,'08:00','09:00','Base Metrô','INTERNO','#6b7280','SIM','SIM','#6b7280',''),
 ('B2',2,'09:00','11:00','Visitas','VISITA','#f59e0b','SIM','SIM','#f59e0b',''),
 ('B3',3,'11:00','11:30','Centro leve','AGENDA','#2563eb','SIM','SIM','#2563eb',''),
 ('B4',4,'11:30','13:00','Almoço / cobertura','ALMOCO','#9ca3af','SIM','SIM','#9ca3af',''),
 ('B5',5,'13:00','14:30','CF principal','AGENDA','#1d4ed8','SIM','SIM','#1d4ed8',''),
 ('B6',6,'14:30','16:30','Centro principal','AGENDA','#0ea5e9','SIM','SIM','#0ea5e9',''),
 ('B7',7,'16:30','17:00','CF complementar','AGENDA','#3b82f6','SIM','SIM','#3b82f6',''),
 ('B8',8,'17:00','17:30','Centro pendente','AGENDA','#38bdf8','SIM','SIM','#38bdf8',''),
 ('B9',9,'17:30','18:00','Fechamento','INTERNO','#64748b','SIM','SIM','#64748b','');
INSERT OR IGNORE INTO crm_locais VALUES
 ('AGF','AGF',10,'SIM','PONTO','LOCAL do Visão 360.','CRM;PROSPECTS'),
 ('BALCAO','BALCÃO',20,'SIM','PONTO','LOCAL do Visão 360.','CRM;PROSPECTS'),
 ('METRO','METRO',30,'SIM','PONTO','LOCAL do Visão 360.','CRM;PROSPECTS');
INSERT OR IGNORE INTO crm_segmentos VALUES ('SEG_ENCOMENDAS','ENCOMENDAS','SIM',1);
