const INTEL_PAGES = {
  gerencial: { action: 'intel_gerencial_bundle', title: 'Gerencial', subtitle: 'Visão executiva da agência', icon: 'monitoring' },
  financeiro: { action: 'intel_financeiro_bundle', title: 'Financeiro', subtitle: 'Qualidade da receita e ticket', icon: 'payments' },
  comercial: { action: 'intel_comercial_bundle', title: 'Comercial', subtitle: 'Funil, conversão e pipeline', icon: 'conversion_path' },
  operacional: { action: 'intel_operacional_bundle', title: 'Operacional', subtitle: 'Volume, mix e execução', icon: 'inventory_2' },
  atendimento: { action: 'intel_atendimento_bundle', title: 'Atendimento', subtitle: 'Interações, dores e objeções', icon: 'support_agent' },
  carteira: { action: 'intel_carteira_bundle', title: 'Carteira', subtitle: 'Retenção, curva e risco', icon: 'group' }
};
function escapeHtml(str) { return String(str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;'); }
function formatMoney(value) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0)); }
function formatShortNumber(value) { return new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 1 }).format(Number(value || 0)); }
function metricValue(card) { const id = card.id || ''; if (id.includes('fat') || id.includes('ticket') || id.includes('margem') || id.includes('custo') || id.includes('lucro')) return formatMoney(card.value); return formatShortNumber(card.value); }
function renderTopbar(container, title, subtitle) {
  container.innerHTML = `<div class="topbar-shell"><div class="topbar"><div class="topbar-left"><a class="logo-circle" href="/intra/" aria-label="Voltar ao painel interno"><img src="/assets/pwa/intra/icon-192.png" alt="Correios" /></a><div class="topbar-title"><h1>${escapeHtml(title)}</h1><p>AGF JOSÉ BONIFÁCIO</p></div></div><div class="topbar-right"><a class="icon-circle" href="/intra/" aria-label="Painel interno"><span class="material-symbols-rounded">home</span></a></div></div></div>`; }
async function loadFilters() { return intelFetchJson('intel_filters'); }
function buildFilterbarHtml(filtersData) { const f = (filtersData && filtersData.filters) || {}; const opt = arr => ['<option value="">Todos</option>'].concat((arr || []).map(v => `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`)).join(''); return `<div class="intel-filterbar"><div class="intel-field"><label>Data inicial</label><input type="date" id="flt-date-from"/></div><div class="intel-field"><label>Data final</label><input type="date" id="flt-date-to"/></div><div class="intel-field"><label>Local</label><select id="flt-local">${opt(f.local)}</select></div><div class="intel-field"><label>Segmento</label><select id="flt-segmento">${opt(f.segmento)}</select></div><div class="intel-field"><label>Tipo</label><select id="flt-tipo">${opt(f.tipo)}</select></div><div class="intel-field"><label>Intermediador</label><select id="flt-intermediador">${opt(f.intermediador)}</select></div><div class="intel-field"><label>Curva</label><select id="flt-curva">${opt(f.curva)}</select></div><div class="intel-field"><label>Responsável</label><select id="flt-responsavel">${opt(f.responsavel)}</select></div><div class="intel-field intel-field--full"><label>Origem</label><select id="flt-origem">${opt(f.origem)}</select></div><div class="intel-field intel-field--full"><label>Canal</label><select id="flt-canal">${opt(f.canal)}</select></div><div class="intel-actions"><button class="intel-btn intel-btn--primary" id="btn-aplicar"><span class="material-symbols-rounded">filter_alt</span>Aplicar</button><button class="intel-btn" id="btn-limpar"><span class="material-symbols-rounded">filter_alt_off</span>Limpar</button></div></div>`; }
function collectFilters() { return { date_from: document.getElementById('flt-date-from')?.value || '', date_to: document.getElementById('flt-date-to')?.value || '', local: document.getElementById('flt-local')?.value || '', segmento: document.getElementById('flt-segmento')?.value || '', tipo: document.getElementById('flt-tipo')?.value || '', intermediador: document.getElementById('flt-intermediador')?.value || '', curva: document.getElementById('flt-curva')?.value || '', responsavel: document.getElementById('flt-responsavel')?.value || '', origem: document.getElementById('flt-origem')?.value || '', canal: document.getElementById('flt-canal')?.value || '' }; }
function attachFilterEvents(onApply) { document.getElementById('btn-aplicar')?.addEventListener('click', () => onApply(collectFilters())); document.getElementById('btn-limpar')?.addEventListener('click', () => { ['date-from','date-to','local','segmento','tipo','intermediador','curva','responsavel','origem','canal'].forEach(id => { const el = document.getElementById(`flt-${id}`); if (el) el.value = ''; }); onApply(collectFilters()); }); }
function renderCards(container, cards) { if (!cards || !cards.length) { container.innerHTML = '<div class="intel-empty">Sem indicadores para este recorte.</div>'; return; } container.innerHTML = '<div class="intel-grid-kpi">' + cards.map(card => `<article class="intel-kpi-card intel-kpi-card--${escapeHtml(card.tone || 'default')}"><div class="intel-kpi-card__label">${escapeHtml(card.label)}</div><div class="intel-kpi-card__value">${metricValue(card)}</div><div class="intel-kpi-card__hint">${escapeHtml(card.hint || '')}</div></article>`).join('') + '</div>'; }
async function renderCharts(container, charts) { if (!charts || !charts.length) { container.innerHTML = '<div class="intel-empty">Sem gráficos para este recorte.</div>'; return; } container.innerHTML = '<div class="intel-grid-charts">' + charts.map(chart => `<section class="intel-chart-card"><div class="intel-card-head"><h3>${escapeHtml(chart.title)}</h3><span class="material-symbols-rounded">bar_chart</span></div><div class="intel-chart-wrap" id="chart-wrap-${escapeHtml(chart.id)}"><canvas id="chart-${escapeHtml(chart.id)}"></canvas></div></section>`).join('') + '</div>'; for (const chart of charts) { const canvas = document.getElementById(`chart-${chart.id}`); await intelRenderChart(canvas, chart); } }
function renderTables(container, tables) { if (!tables || !tables.length) { container.innerHTML = ''; return; } container.innerHTML = tables.map(tbl => { const rows = tbl.rows || []; const headers = rows.length ? Object.keys(rows[0]) : []; return `<section class="intel-table-card"><div class="intel-card-head"><h3>${escapeHtml(tbl.title)}</h3><span class="material-symbols-rounded">table</span></div><div class="intel-table-responsive"><table class="intel-table"><thead><tr>${headers.map(h => `<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${headers.map(h => `<td>${escapeHtml(row[h])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`; }).join(''); }
function renderNotes(container, notes) { if (!notes || !notes.length) { container.innerHTML = ''; return; } container.innerHTML = `<section class="intel-note-card"><div class="intel-card-head"><h3>Observações</h3><span class="material-symbols-rounded">info</span></div><ul>${notes.map(n => `<li>${escapeHtml(n)}</li>`).join('')}</ul></section>`; }
async function bootIntelPage(pageKey) { const page = INTEL_PAGES[pageKey]; renderTopbar(document.getElementById('topbar-root'), page.title, page.subtitle); const filterData = await loadFilters(); document.getElementById('filters-root').innerHTML = buildFilterbarHtml(filterData); attachFilterEvents(async (filters) => { await loadIntelBundle(pageKey, filters); }); await loadIntelBundle(pageKey, {}); }
async function loadIntelBundle(pageKey, filters) { const page = INTEL_PAGES[pageKey]; const cardsRoot = document.getElementById('cards-root'); const chartsRoot = document.getElementById('charts-root'); const tablesRoot = document.getElementById('tables-root'); const notesRoot = document.getElementById('notes-root'); cardsRoot.innerHTML = '<div class="intel-loading">Carregando indicadores…</div>'; chartsRoot.innerHTML = ''; tablesRoot.innerHTML = ''; notesRoot.innerHTML = ''; try { const data = await intelFetchJson(page.action, filters || {}); renderCards(cardsRoot, data.cards || []); await renderCharts(chartsRoot, data.charts || []); renderTables(tablesRoot, data.tables || []); renderNotes(notesRoot, data.notes || []); } catch (err) { cardsRoot.innerHTML = `<div class="intel-empty">${escapeHtml(err.message || 'Falha ao carregar.')}</div>`; } }
function renderIntelHub() { renderTopbar(document.getElementById('topbar-root'), 'Inteligência', 'Nova camada analítica sem regressão'); document.getElementById('hub-root').innerHTML = '<div class="intel-nav-grid">' + Object.entries(INTEL_PAGES).map(([key, page]) => `<a class="intel-nav-card" href="./${key}/index.html"><div class="intel-nav-icon"><span class="material-symbols-rounded">${page.icon}</span></div><div class="intel-nav-copy"><h3>${page.title}</h3><p>${page.subtitle}</p></div><div class="intel-nav-arrow"><span class="material-symbols-rounded">chevron_right</span></div></a>`).join('') + '</div>'; }


