// ============================================================
//  ATENDE - CONFIGURACAO CENTRAL
//  ATENCAO SENSIVEL: este modulo processa dados pessoais de
//  remetentes/destinatarios e usa PropertiesService para IDs/tokens.
// ============================================================

var ATENDE_CONFIG = {
  APP_NAME: 'Postagens - AGF Jose Bonifacio',
  TIMEZONE: 'America/Fortaleza',
  PROP_SPREADSHEET_ID: 'SPREADSHEET_ID',
  PROP_LEGACY_SPREADSHEET_ID: 'SS_ID',
  PROP_INGEST_TOKEN: 'INGEST_TOKEN',
  CACHE_SECONDS: 120,
  CACHE_MAX_CHARS: 90000,
  DEFAULT_FRONT_DAYS: 7,
  REQUIRE_FRONT_DATE_FILTER: false,
  SHEETS: {
    CONFIG: 'CONFIG',
    RAW_ATENDIMENTOS: 'RAW_ATENDIMENTOS',
    RAW_OBJETOS_CAPTADOS: 'RAW_OBJETOS_CAPTADOS',
    POSTAGENS: 'Postagens',
    EVENTOS_OBJETOS: 'EVENTOS_OBJETOS',
    LOG_IMPORTACOES: 'LOG_IMPORTACOES',
    ERROS: 'ERROS',
  },
};

var ATENDE_FIELD_DEFS = [
  ['dtAtendimento', 'Data'],
  ['idAtendente', 'Atendente'],
  ['codObjeto', 'Objeto'],
  ['codigoAtendimento', 'codigo'],
  ['descricaoAtendimento', 'descricao'],
  ['categoria', 'Categoria'],
  ['contrato', 'Contrato'],
  ['cartaoPostagem', 'Cartão Postagem'],
  ['rem_nome', 'Remetente'],
  ['rem_documento', 'Rem. Documento'],
  ['valorPostagem', 'Valor'],
  ['formaPagamento', 'Forma Pagamento'],
  ['peso', 'Peso (kg)'],
  ['largura', 'Larg. (cm)'],
  ['comprimento', 'Comp. (cm)'],
  ['altura', 'Alt. (cm)'],
  ['diametro', 'Diâm. (cm)'],
  ['valorDeclarado', 'VD'],
  ['formato', 'Formato'],
  ['rem_cep', 'Rem. CEP'],
  ['rem_logradouro', 'Rem. Logradouro'],
  ['rem_numero', 'Rem. Número'],
  ['rem_complemento', 'Rem. Comp'],
  ['rem_bairro', 'Rem. Bairro'],
  ['rem_cidade', 'Rem. Cidade'],
  ['rem_uf', 'Rem. UF'],
  ['rem_telefone', 'Rem. Telefone'],
  ['dest_nome', 'Dest. Nome'],
  ['dest_documento', 'Dest. Documento'],
  ['dest_cep', 'Dest. CEP'],
  ['dest_logradouro', 'Dest. Logradouro'],
  ['dest_numero', 'Dest. Número'],
  ['dest_complemento', 'Dest. Complemento'],
  ['dest_bairro', 'Dest. Bairro'],
  ['dest_cidade', 'Dest. Cidade'],
  ['dest_uf', 'Dest. UF'],
  ['origem', 'Tipo Postagem'],
  ['statusDesc', 'Status'],
  ['dtPrevista', 'Prev. Entrega'],
  ['tipoAtendimento', 'tipo'],
  ['formaPagamentoAtendimento', 'formaPagamento'],
];

var ATENDE_POSTAGENS_HEADERS = ATENDE_FIELD_DEFS.map(function(def) { return def[1]; });

var ATENDE_SOURCE_ALIASES = {
  'Cartão Postagem': ['Cartao Postagem'],
  'Diâm. (cm)': ['Diam. (cm)'],
  'Rem. Número': ['Rem. Numero'],
  'Dest. Número': ['Dest. Numero'],
};

var ATENDE_COLUMN_WIDTHS = {
  'Data': 145,
  'Atendente': 145,
  'Objeto': 155,
  'codigo': 88,
  'descricao': 185,
  'Categoria': 120,
  'Contrato': 112,
  'Cartão Postagem': 125,
  'Remetente': 215,
  'Rem. Documento': 140,
  'Valor': 145,
  'Forma Pagamento': 145,
  'Peso (kg)': 88,
  'Larg. (cm)': 88,
  'Comp. (cm)': 92,
  'Alt. (cm)': 82,
  'Diâm. (cm)': 90,
  'VD': 145,
  'Formato': 105,
  'Rem. CEP': 95,
  'Rem. Logradouro': 210,
  'Rem. Número': 100,
  'Rem. Comp': 150,
  'Rem. Bairro': 150,
  'Rem. Cidade': 145,
  'Rem. UF': 70,
  'Rem. Telefone': 135,
  'Dest. Nome': 215,
  'Dest. Documento': 140,
  'Dest. CEP': 95,
  'Dest. Logradouro': 210,
  'Dest. Número': 100,
  'Dest. Complemento': 150,
  'Dest. Bairro': 150,
  'Dest. Cidade': 145,
  'Dest. UF': 70,
  'Tipo Postagem': 125,
  'Status': 230,
  'Prev. Entrega': 120,
  'tipo': 205,
  'formaPagamento': 155,
};

var ATENDE_TEXT_COLUMNS = [
  'Atendente', 'Objeto', 'codigo', 'Contrato', 'Cartão Postagem',
  'Rem. Documento', 'Rem. CEP', 'Rem. Número', 'Rem. Telefone',
  'Dest. Documento', 'Dest. CEP', 'Dest. Número',
  'tipo', 'formaPagamento',
];
