(function(){
'use strict';
const auth=window.AgfAuth,ui=window.AgfUi,form=document.getElementById('iconsForm'),host=document.getElementById('iconsGrid'),status=document.getElementById('iconsStatus'),search=document.getElementById('iconSearch'),count=document.getElementById('iconsCount');
const catalog=ui.getCatalog();let current=null;let query='';
const esc=(value)=>String(value||'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const lists=(cfg)=>({icons:new Set((cfg.customized&&cfg.customized.icons)||[]),colors:new Set((cfg.customized&&cfg.customized.colors)||[])});
function setStatus(message,isError){status.textContent=message||'';status.style.color=isError?'#b42318':'#60788d';}
function normalize(config){const merged=JSON.parse(JSON.stringify(ui.fallback));Object.assign(merged.colors,config&&config.colors||{});Object.assign(merged.icons,config&&config.icons||{});merged.version=Math.max(2,Number(config&&config.version||2));merged.customized={colors:[...new Set(config&&config.customized&&config.customized.colors||[])],icons:[...new Set(config&&config.customized&&config.customized.icons||[])]};return merged;}
function matches(item){const hay=(item.label+' '+item.key+' '+item.icon+' '+(item.searchTerms||'')).toLowerCase();return !query||hay.includes(query);}
function row(item,custom){const icon=current.icons[item.key]||item.icon,color=current.colors[item.key]||item.color,isCustom=custom.icons.has(item.key)||custom.colors.has(item.key);return `<article class="icon-row${isCustom?' is-custom':''}" data-key="${esc(item.key)}"><span class="icon-preview"><span class="material-symbols-rounded" style="color:${esc(color)}">${esc(icon)}</span></span><div class="icon-fields"><div class="icon-title"><strong>${esc(item.label)}</strong><code>${esc(item.key)}</code></div><div class="mini-fields"><label class="mini-field"><span>Símbolo</span><input data-kind="icon" data-key="${esc(item.key)}" type="text" value="${esc(icon)}" pattern="[a-z0-9_]{2,60}" required></label><label class="mini-field"><span>Cor</span><input data-kind="color" data-key="${esc(item.key)}" type="color" value="${esc(color)}" required></label></div></div></article>`;}
function render(config){current=normalize(config);const custom=lists(current);const visible=catalog.filter(matches);const groups=[...new Set(visible.map(x=>x.group))];host.innerHTML=groups.map((group)=>{const items=visible.filter(x=>x.group===group);return `<section class="icon-group"><h2 class="icon-group-title">${esc(group)} <span>${items.length}</span></h2><div class="icons-grid">${items.map(x=>row(x,custom)).join('')}</div></section>`;}).join('')||'<p>Nenhum ícone encontrado.</p>';count.textContent=String(visible.length);host.querySelectorAll('input').forEach((input)=>input.addEventListener('input',preview));}
function preview(event){const input=event.target,row=input.closest('.icon-row'),key=input.dataset.key,item=catalog.find(x=>x.key===key),iconInput=row.querySelector('[data-kind=icon]'),colorInput=row.querySelector('[data-kind=color]'),icon=iconInput.value.trim(),color=colorInput.value,previewNode=row.querySelector('.icon-preview .material-symbols-rounded');previewNode.textContent=icon||'help';previewNode.style.color=color;current.icons[key]=icon;current.colors[key]=color;const custom=lists(current);if(icon!==item.icon)custom.icons.add(key);else custom.icons.delete(key);if(color.toUpperCase()!==item.color.toUpperCase())custom.colors.add(key);else custom.colors.delete(key);current.customized={icons:[...custom.icons],colors:[...custom.colors]};row.classList.toggle('is-custom',custom.icons.has(key)||custom.colors.has(key));}
function build(){current.version=Number(current.version||2)+1;return current;}
async function load(){try{const local=auth.getLocalSession();if(!local||local.payload.role!=='admin')throw new Error('Acesso permitido somente para administrador.');const validated=await auth.validate();if(validated.user.role!=='admin')throw new Error('Acesso permitido somente para administrador.');const result=await auth.getUiConfig();render(result.config);setStatus(catalog.length+' ícones encontrados e carregados.');}catch(err){setStatus(err.message,true);setTimeout(()=>auth.redirectToLogin('perfil'),900);}}
search.addEventListener('input',()=>{query=search.value.trim().toLowerCase();render(current);});
document.getElementById('resetButton').addEventListener('click',()=>{current=normalize(ui.fallback);render(current);setStatus('Padrões restaurados localmente. Clique em Salvar para confirmar.');});
document.getElementById('reloadButton').addEventListener('click',load);
form.addEventListener('submit',async(event)=>{event.preventDefault();setStatus('Salvando…');try{const result=await auth.saveUiConfig(build());render(result.config);ui.applyAll(result.config);setStatus('Biblioteca atualizada. As páginas usarão os novos ícones e cores.');}catch(err){setStatus(err.message,true);}});
document.getElementById('logoutButton').addEventListener('click',async()=>{await auth.logout();auth.redirectToLogin('login');});load();
})();